const A=AssistantClient,$=id=>document.getElementById(id),isExtension=!!globalThis.chrome?.runtime?.id;
const fields=["engine","model_path","engine_path","ffmpeg_path","device","compute_type","language","hotwords","deepseek_model","analysis_window"];
let loaded=false,dirty=false,mobile=null;
function installMobilePanel(){const panel=$("panel-notifications"),preview=panel.querySelector(".preview-box"),style=document.createElement("style");style.textContent=".mobile-pairing{display:grid;grid-template-columns:164px 1fr;gap:24px;align-items:center;padding:22px 0 4px}.mobile-pairing img{width:164px;height:164px;border:1px solid var(--line);border-radius:18px;background:#fff;padding:9px}.mobile-pairing strong{font-size:14px}.mobile-pairing .row{justify-content:flex-start;flex-wrap:wrap}.mobile-pair-card>.primary{margin-top:20px}@media(max-width:600px){.mobile-pairing{grid-template-columns:1fr}.mobile-pairing img{margin:auto}}";document.head.append(style);preview.insertAdjacentHTML("afterend",`<div class="card mobile-pair-card"><div class="section-label"><span class="icon-tile purple" data-icon="bell"></span><h2>手机课堂提醒</h2></div><div class="setting-row"><div><strong id="mobile-label">允许发送到手机</strong><p id="mobile-state">尚未配对手机。</p></div><label class="toggle"><input id="mobile-enabled" type="checkbox" aria-labelledby="mobile-label" disabled><span class="switch"></span></label></div><div id="mobile-pairing" class="mobile-pairing" hidden><img id="mobile-qr" alt="手机课堂提醒配对二维码"><div><strong>打开“SCUT 课堂提醒”App 扫码</strong><p class="footnote">配对信息只保存在本机和手机。也可以复制配对码后在 App 中粘贴。</p><div class="row"><button id="copy-mobile-code">复制配对码</button><button id="test-mobile">发送测试提醒</button></div></div></div><button id="setup-mobile" class="primary">生成手机配对码</button><p class="footnote">需要先配置 DeepSeek Key。手机监听时会显示常驻状态通知；锁屏后仍能收到点名、扫码、提问、作业、测验、安排和评分提醒。</p></div>`);AssistantUI.icons();$("setup-mobile").onclick=()=>act("setup-mobile",async()=>{mobile=await A.api("/api/mobile/setup",{method:"POST"});renderMobile();message("手机配对码已生成。安装 App 后扫码即可。");});$("copy-mobile-code").onclick=()=>act("copy-mobile-code",async()=>{await navigator.clipboard.writeText(mobile.pairing_code);AssistantUI.toast("手机配对码已复制");});$("test-mobile").onclick=()=>act("test-mobile",async()=>{await A.api("/api/mobile/test",{method:"POST",timeout:20000});message("测试提醒已送到加密信箱，请查看手机通知。");});$("mobile-enabled").onchange=async()=>{const wanted=$("mobile-enabled").checked;try{await A.api("/api/mobile/enabled",{method:"POST",body:{enabled:wanted}});await loadMobile();AssistantUI.toast(wanted?"手机提醒已开启":"手机提醒已暂停");}catch(e){$("mobile-enabled").checked=!wanted;message(e.message,true);}};}
function renderMobile(){const configured=!!mobile?.configured;$("mobile-enabled").disabled=!configured;$("mobile-enabled").checked=!!mobile?.enabled;$("mobile-state").textContent=!configured?"尚未配对手机。":mobile.enabled?(mobile.last_error?"发送暂时中断："+mobile.last_error:mobile.pending?`已开启 · ${mobile.pending} 条等待发送`:"已开启 · 重要信息会推送到手机"):"已配对，当前暂停发送";$("setup-mobile").hidden=configured;$("mobile-pairing").hidden=!configured;if(configured){$("mobile-qr").src=mobile.pairing_qr;$("test-mobile").disabled=!mobile.enabled;}}
async function loadMobile(){mobile=await A.api("/api/mobile");renderMobile();}
function message(text,error=false){$("message").textContent=text;$("message").className="notice"+(error?" error":"");}
function markDirty(value){dirty=value;$("save-bar").classList.toggle("dirty",value);$("save-state").textContent=value?"有新的调整，记得保存":"设置保存在你的电脑上";$("save").disabled=!loaded||!value;}
function reflect(cfg){$("key-state").dataset.ready=String(cfg.deepseek_configured);$("test-key").disabled=!cfg.deepseek_configured;$("key-check-result").textContent=cfg.deepseek_check?cfg.deepseek_check.message+" · "+new Date(cfg.deepseek_check.checked_at*1000).toLocaleTimeString():"尚未检测。读取到 Key 不代表远程连接已经验证。";for(const key of fields)$(key).value=cfg[key];$("retain_audio").checked=cfg.retain_audio;$("media_hosts").value=cfg.media_hosts.join("\n");$("key-state").textContent=cfg.deepseek_configured?(cfg.deepseek_key_status==="environment"?"已识别环境变量中的 Key":"Key 已保存到本机，重启和升级后无需重新填写。"):(cfg.deepseek_key_status==="unreadable"?"本机密钥无法解密，请在当前 Windows 账户下重新保存。":"尚未保存 Key；本地字幕仍可独立使用。");$("deepseek_key").placeholder=cfg.deepseek_configured?"已保存 · 留空保持不变，填入可替换":"粘贴 DeepSeek API Key";$("key-location").textContent=cfg.deepseek_key_location?"加密文件："+cfg.deepseek_key_location:"";$("output").textContent="结果保存在 "+cfg.output_path;loaded=true;}
async function diagnostics(){const h=await A.api("/api/health");$("diagnostics").textContent=`模型：${h.asr.model_exists?"已找到":"未找到"} · XXL：${h.asr.exe_exists?"已找到":"未找到"} · FFmpeg：${h.asr.ffmpeg_exists?"已找到":"未找到"} · 常驻模型：${h.asr.loaded?"已加载":"未加载"}`;$("model-status").textContent=h.asr.fallback_reason?h.asr.fallback_reason:h.asr.loaded?"模型已加载，可以开始听课":h.asr.model_exists?"已找到本地语音模型":"尚未找到模型，请检查路径";}
function modelControls(){const model=$("deepseek_model").value;$("deepseek-preset").value=[...$("deepseek-preset").options].some(o=>o.value===model)?model:"custom";$("custom-model-field").hidden=$("deepseek-preset").value!=="custom";$("speech-preset").value=[...$("speech-preset").options].some(o=>o.value===$("model_path").value)?$("model_path").value:"custom";}
async function load(){reflect(await A.api("/api/settings"));try{const models=await A.api("/api/models");$("speech-preset").replaceChildren(...models.speech.map(m=>new Option(m.name,m.path)),new Option("自定义模型路径","custom"));$("deepseek-preset").replaceChildren(...models.deepseek.map(m=>new Option(m==="deepseek-flash"?"DeepSeek V4.1 Flash":m==="deepseek-v4-pro"?"DeepSeek V4 Pro":m,m)),new Option("自定义模型名","custom"));}catch{$("speech-preset").replaceChildren(new Option("当前模型路径","custom"));}modelControls();await diagnostics();await loadMobile();markDirty(false);}
$("deepseek-preset").onchange=()=>{const choice=$("deepseek-preset").value;$("custom-model-field").hidden=choice!=="custom";if(choice!=="custom")$("deepseek_model").value=choice;markDirty(true);};
$("speech-preset").onchange=()=>{if($("speech-preset").value!=="custom"){$("model_path").value=$("speech-preset").value;markDirty(true);}else{$("model_path").closest("details").open=true;$("model_path").focus();}};
async function act(id,fn){const button=$(id);button.disabled=true;button.classList.add("busy");button.setAttribute("aria-busy","true");try{await fn();}catch(e){message(e.message,true);}finally{button.classList.remove("busy");button.removeAttribute("aria-busy");button.disabled=id==="save"?(!loaded||!dirty):false;}}
$("connect").onclick=()=>act("connect",async()=>{const token=$("token").value.trim();if(!token)throw new Error("请先粘贴从本地面板复制的连接口令。");await A.fetchWithToken(token,"/api/health");await A.setConnection(token);await load();$("token").value="";message("已连接本地服务。可以开始实时字幕，或调整识别与分析偏好。");AssistantUI.toast("连接成功");});
$("local-connection").hidden=isExtension;$("extension-connection").hidden=!isExtension;$("copy-token").hidden=isExtension;
$("copy-token").onclick=()=>act("copy-token",async()=>{const result=await A.api("/api/pairing-token");await navigator.clipboard.writeText(result.token);message("口令已复制。打开工具栏中的 SCUT 课堂助手 → 偏好设置 → 连接与安装，粘贴并连接。");AssistantUI.toast("扩展连接口令已复制");});
for(const id of [...fields,"retain_audio","media_hosts","deepseek_key"])$(id).addEventListener("input",()=>{if(loaded)markDirty(true);});
$("save").onclick=()=>act("save",async()=>{for(const id of fields){if(!$(id).checkValidity()){AssistantUI.selectPanel($(id).closest(".settings-panel").id.replace("panel-",""));$(id).reportValidity();return;}}const patch=Object.fromEntries(fields.map(k=>[k,$(k).value]));patch.analysis_window=Number(patch.analysis_window);patch.retain_audio=$("retain_audio").checked;patch.media_hosts=$("media_hosts").value.split(/\s+/).filter(Boolean);if($("deepseek_key").value.trim())patch.deepseek_key=$("deepseek_key").value.trim();const cfg=await A.api("/api/settings",{method:"POST",body:patch});$("deepseek_key").value="";reflect(cfg);markDirty(false);message("设置已保存。语音参数会在下一段识别时生效。");AssistantUI.toast("设置已保存");});
$("clear-key").onclick=()=>act("clear-key",async()=>{const cfg=await A.api("/api/settings",{method:"POST",body:{clear_deepseek_key:true}});$("deepseek_key").value="";reflect(cfg);message("已清除本地保存的 Key；环境变量如有配置，仍会优先使用。");});
$("test-key").onclick=()=>act("test-key",async()=>{if(dirty)throw new Error("请先保存 Key 和模型，再检测已保存的配置。");$("key-check-result").textContent="正在验证 Key 与模型…";const result=await A.api("/api/deepseek/check",{method:"POST",timeout:15000});$("key-check-result").textContent=result.message+" · "+new Date(result.checked_at*1000).toLocaleTimeString();});
$("warmup").onclick=()=>act("warmup",async()=>{if(dirty)throw new Error("请先保存设置，再按当前配置预加载模型。");message("正在加载本地模型，首次加载可能需要十几秒…");await A.api("/api/warmup",{method:"POST",timeout:120000});await diagnostics();message("模型已预加载，可以直接开始实时字幕。");AssistantUI.toast("语音模型已就绪");});
$("desktopAlerts").onchange=async()=>{if(!globalThis.chrome?.permissions){$("desktopAlerts").checked=false;message("请在浏览器扩展的偏好设置中开启桌面通知。",true);return;}try{const enabled=$("desktopAlerts").checked;const granted=!enabled||await chrome.permissions.request({permissions:["notifications"]});$("desktopAlerts").checked=enabled&&granted;await chrome.storage.local.set({desktopAlerts:enabled&&granted});AssistantUI.toast(granted?(enabled?"桌面通知已开启":"桌面通知已关闭"):"未授予通知权限，课堂浮层仍可用");}catch(e){$("desktopAlerts").checked=false;message(e.message,true);}};
installMobilePanel();
(async()=>{try{const token=new URLSearchParams(location.hash.slice(1)).get("token");if(token){await A.setConnection(token);history.replaceState(null,"",location.pathname);AssistantUI.selectPanel("connection");}const cfg=await A.connection();$("desktopAlerts").checked=!!cfg.desktopAlerts;if(cfg.token||!isExtension){await load();message("本地服务已连接。");}else message("先从本地面板复制连接口令，粘贴到下方完成配对。");}catch(e){message(e.message,true);}})();
