const A=AssistantClient,$=id=>document.getElementById(id),isExtension=!!globalThis.chrome?.runtime?.id;
const fields=["engine","model_path","engine_path","ffmpeg_path","device","compute_type","language","hotwords","deepseek_model","analysis_window"];
let loaded=false,dirty=false;
function message(text,error=false){$("message").textContent=text;$("message").className="notice"+(error?" error":"");}
function markDirty(value){dirty=value;$("save-bar").classList.toggle("dirty",value);$("save-state").textContent=value?"有新的调整，记得保存":"设置保存在你的电脑上";$("save").disabled=!loaded||!value;}
function reflect(cfg){for(const key of fields)$(key).value=cfg[key];$("retain_audio").checked=cfg.retain_audio;$("media_hosts").value=cfg.media_hosts.join("\n");$("key-state").textContent=cfg.deepseek_configured?(cfg.deepseek_key_status==="environment"?"已连接环境变量中的 Key":"Key 已保存到本机，重启和升级后无需重新填写。"):(cfg.deepseek_key_status==="unreadable"?"本机密钥无法解密，请在当前 Windows 账户下重新保存。":"尚未保存 Key；本地字幕仍可独立使用。");$("deepseek_key").placeholder=cfg.deepseek_configured?"已保存 · 留空保持不变，填入可替换":"粘贴 DeepSeek API Key";$("key-location").textContent=cfg.deepseek_key_location?"加密文件："+cfg.deepseek_key_location:"";$("output").textContent="结果保存在 "+cfg.output_path;loaded=true;}
async function diagnostics(){const h=await A.api("/api/health");$("diagnostics").textContent=`模型：${h.asr.model_exists?"已找到":"未找到"} · XXL：${h.asr.exe_exists?"已找到":"未找到"} · FFmpeg：${h.asr.ffmpeg_exists?"已找到":"未找到"} · 常驻模型：${h.asr.loaded?"已加载":"未加载"}`;$("model-status").textContent=h.asr.loaded?"模型已加载，可以开始听课":h.asr.model_exists?"已找到本地语音模型":"尚未找到模型，请检查路径";}
function modelControls(){const model=$("deepseek_model").value;$("deepseek-preset").value=["deepseek-v4-flash","deepseek-v4-pro"].includes(model)?model:"custom";$("custom-model-field").hidden=$("deepseek-preset").value!=="custom";$("speech-preset").value=[...$("speech-preset").options].some(o=>o.value===$("model_path").value)?$("model_path").value:"custom";}
async function load(){reflect(await A.api("/api/settings"));try{const models=await A.api("/api/models");$("speech-preset").replaceChildren(...models.speech.map(m=>new Option(m.name,m.path)),new Option("自定义模型路径","custom"));}catch{$("speech-preset").replaceChildren(new Option("当前模型路径","custom"));}modelControls();await diagnostics();markDirty(false);}
$("deepseek-preset").onchange=()=>{const choice=$("deepseek-preset").value;$("custom-model-field").hidden=choice!=="custom";if(choice!=="custom")$("deepseek_model").value=choice;markDirty(true);};
$("speech-preset").onchange=()=>{if($("speech-preset").value!=="custom"){$("model_path").value=$("speech-preset").value;markDirty(true);}else{$("model_path").closest("details").open=true;$("model_path").focus();}};
async function act(id,fn){const button=$(id);button.disabled=true;button.classList.add("busy");button.setAttribute("aria-busy","true");try{await fn();}catch(e){message(e.message,true);}finally{button.classList.remove("busy");button.removeAttribute("aria-busy");button.disabled=id==="save"?(!loaded||!dirty):false;}}
$("connect").onclick=()=>act("connect",async()=>{const token=$("token").value.trim();if(!token)throw new Error("请先粘贴从本地面板复制的连接口令。");await A.fetchWithToken(token,"/api/health");await A.setConnection(token);await load();$("token").value="";message("已连接本地服务。可以开始实时字幕，或调整识别与分析偏好。");AssistantUI.toast("连接成功");});
$("local-connection").hidden=isExtension;$("extension-connection").hidden=!isExtension;$("copy-token").hidden=isExtension;
$("copy-token").onclick=()=>act("copy-token",async()=>{const result=await A.api("/api/pairing-token");await navigator.clipboard.writeText(result.token);message("口令已复制。打开工具栏中的 SCUT 课堂助手 → 偏好设置 → 连接与安装，粘贴并连接。");AssistantUI.toast("扩展连接口令已复制");});
for(const id of [...fields,"retain_audio","media_hosts","deepseek_key"])$(id).addEventListener("input",()=>{if(loaded)markDirty(true);});
$("save").onclick=()=>act("save",async()=>{for(const id of fields){if(!$(id).checkValidity()){AssistantUI.selectPanel($(id).closest(".settings-panel").id.replace("panel-",""));$(id).reportValidity();return;}}const patch=Object.fromEntries(fields.map(k=>[k,$(k).value]));patch.analysis_window=Number(patch.analysis_window);patch.retain_audio=$("retain_audio").checked;patch.media_hosts=$("media_hosts").value.split(/\s+/).filter(Boolean);if($("deepseek_key").value.trim())patch.deepseek_key=$("deepseek_key").value.trim();const cfg=await A.api("/api/settings",{method:"POST",body:patch});$("deepseek_key").value="";reflect(cfg);markDirty(false);message("设置已保存。语音参数会在下一段识别时生效。");AssistantUI.toast("设置已保存");});
$("clear-key").onclick=()=>act("clear-key",async()=>{const cfg=await A.api("/api/settings",{method:"POST",body:{clear_deepseek_key:true}});$("deepseek_key").value="";reflect(cfg);message("已清除本地保存的 Key；环境变量如有配置，仍会优先使用。");});
$("warmup").onclick=()=>act("warmup",async()=>{if(dirty)throw new Error("请先保存设置，再按当前配置预加载模型。");message("正在加载本地模型，首次加载可能需要十几秒…");await A.api("/api/warmup",{method:"POST",timeout:120000});await diagnostics();message("模型已预加载，可以直接开始实时字幕。");AssistantUI.toast("语音模型已就绪");});
$("desktopAlerts").onchange=async()=>{if(!globalThis.chrome?.permissions){$("desktopAlerts").checked=false;message("请在浏览器扩展的偏好设置中开启桌面通知。",true);return;}try{const enabled=$("desktopAlerts").checked;const granted=!enabled||await chrome.permissions.request({permissions:["notifications"]});$("desktopAlerts").checked=enabled&&granted;await chrome.storage.local.set({desktopAlerts:enabled&&granted});AssistantUI.toast(granted?(enabled?"桌面通知已开启":"桌面通知已关闭"):"未授予通知权限，课堂浮层仍可用");}catch(e){$("desktopAlerts").checked=false;message(e.message,true);}};
(async()=>{try{const token=new URLSearchParams(location.hash.slice(1)).get("token");if(token){await A.setConnection(token);history.replaceState(null,"",location.pathname);AssistantUI.selectPanel("connection");}const cfg=await A.connection();$("desktopAlerts").checked=!!cfg.desktopAlerts;if(cfg.token||!isExtension){await load();message("本地服务已连接。");}else message("先从本地面板复制连接口令，粘贴到下方完成配对。");}catch(e){message(e.message,true);}})();
